server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.219.107:25668/highgarden_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: highgarden
    password: tiger

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
