server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(+7ESt6su6UIVH9S8E/dApG3e+zgWZgidrwX2UJNoNjfquSQxhJRwtGAffQzhpXBOldhuKroAWxWH0fQfEzChNug4Ac50MOjyWmXPAg+hqxZw7eO7nl7d/pfC1QNgz5zLm29IWOpQccg84NIup2pRkA==)
    username: ENC(uUiiSpCmtq/iqGL/o0dMUGIBibZ9XuOU)
    password: ENC(yKYIZLll6KdTkUL6A+XmcA==)

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

# jasypt
jasypt:
  encryptor:
    bean: jasyptStringEncryptor